import "./main.scss"
import "./hamburger-icon.css"
import "./scroll-animations"
import "./hamburger.js"
import "./background-scroll.js"
import "./intro-animation.js"
import "./modal.js"
import "./modal.scss"